// Generated by scripts/build-runtime.mjs. Edit src/runtime/chatgpt-core.js.
const CONVOGLIDE_ROOT_ID = "convoglide-root";
const CONVOGLIDE_CONVERSATION_RESPONSE_RE = /\/backend-api\/conversation\/[0-9a-f-]+(?:\?|$)/i;
const CONVOGLIDE_DEFAULT_MAX_MESSAGE_NODES = 8;
const CONVOGLIDE_MIN_MAX_MESSAGE_NODES = 4;
const CONVOGLIDE_DEFAULT_BOOTSTRAP_MAX_MESSAGE_NODES = 4;
const CONVOGLIDE_MIN_BOOTSTRAP_MESSAGE_NODES = 2;
const CONVOGLIDE_DEFAULT_BOOTSTRAP_TURN_WINDOW = 3;
const CONVOGLIDE_MIN_BOOTSTRAP_TURN_WINDOW = 1;
const CONVOGLIDE_DEFAULT_KEEP_TAIL_TURNS = 12;
const CONVOGLIDE_DEFAULT_VIEWPORT_BUFFER_PX = 1800;
const CONVOGLIDE_DEFAULT_MIN_TURN_HEIGHT_PX = 160;
const CONVOGLIDE_DEFAULT_HEAVY_BLOCK_BUFFER_PX = 1200;
const CONVOGLIDE_DEFAULT_HEAVY_BLOCK_MIN_HEIGHT_PX = 260;
const CONVOGLIDE_DEFAULT_HEAVY_BLOCK_MIN_TEXT_LENGTH = 1400;
const CONVOGLIDE_DEFAULT_POST_LOAD_START_DELAY_MS = 900;
const CONVOGLIDE_DEFAULT_POST_LOAD_FALLBACK_DELAY_MS = 30000;
const CONVOGLIDE_CONVERSATION_CACHE_STORAGE_KEY = "convoglide:conversation-cache";
const CONVOGLIDE_DEFAULT_CONVERSATION_CACHE_TTL_MS = 30 * 60 * 1000;
const CONVOGLIDE_DEFAULT_CONVERSATION_CACHE_MAX_ENTRIES = 3;
const CONVOGLIDE_THREAD_SELECTORS = ["#thread", "main"];

function convoglideCloneValue(value) {
  return globalThis.structuredClone ? globalThis.structuredClone(value) : JSON.parse(JSON.stringify(value));
}

function convoglideIsMessageNode(node) {
  return !!node?.message;
}

function convoglideGetMessageRole(node) {
  return node?.message?.author?.role || null;
}

function convoglideIsUserFacingMessageNode(node) {
  const role = convoglideGetMessageRole(node);
  return role === "user" || role === "assistant";
}

function convoglideExtractActiveBranchIds(payload) {
  const mapping = payload?.mapping;
  const currentNode = payload?.current_node;
  if (!mapping || typeof mapping !== "object" || !currentNode) {
    return [];
  }

  const branch = [];
  const seen = new Set();
  let cursor = currentNode;

  while (cursor && mapping[cursor] && !seen.has(cursor)) {
    branch.push(cursor);
    seen.add(cursor);
    cursor = mapping[cursor].parent;
  }

  branch.reverse();
  return branch;
}

function convoglideResolveBootstrapMaxMessageNodes(maxMessageNodes, options = {}) {
  const bootstrapMax = Number.isFinite(options.bootstrapMaxMessageNodes)
    ? Math.max(CONVOGLIDE_MIN_BOOTSTRAP_MESSAGE_NODES, Math.floor(options.bootstrapMaxMessageNodes))
    : CONVOGLIDE_DEFAULT_BOOTSTRAP_MAX_MESSAGE_NODES;

  return Math.min(Math.max(CONVOGLIDE_MIN_BOOTSTRAP_MESSAGE_NODES, Math.floor(maxMessageNodes)), bootstrapMax);
}

function convoglideResolveBootstrapTurnWindow(maxMessageNodes, options = {}) {
  const bootstrapTurnWindow = Number.isFinite(options.bootstrapTurnWindow)
    ? Math.max(CONVOGLIDE_MIN_BOOTSTRAP_TURN_WINDOW, Math.floor(options.bootstrapTurnWindow))
    : CONVOGLIDE_DEFAULT_BOOTSTRAP_TURN_WINDOW;
  const maxVisibleMessages = Math.max(CONVOGLIDE_MIN_MAX_MESSAGE_NODES, Math.floor(maxMessageNodes || 0));
  const maxTurnWindow = Math.max(
    CONVOGLIDE_MIN_BOOTSTRAP_TURN_WINDOW,
    Math.ceil(maxVisibleMessages / 2),
  );
  return Math.min(bootstrapTurnWindow, maxTurnWindow);
}

function convoglideFindTurnWindowStartIndex(branch, mapping, turnCount) {
  const normalizedTurnCount = Number.isFinite(turnCount) ? Math.max(1, Math.floor(turnCount)) : 0;
  if (!normalizedTurnCount) {
    return 0;
  }

  const userIndexes = [];
  for (let index = 0; index < branch.length; index += 1) {
    if (convoglideGetMessageRole(mapping[branch[index]]) === "user") {
      userIndexes.push(index);
    }
  }

  if (!userIndexes.length) {
    return 0;
  }

  const targetOffset = Math.max(0, userIndexes.length - normalizedTurnCount);
  return userIndexes[targetOffset] || 0;
}

function convoglideTrimConversationPayload(payload, maxMessageNodes, options = {}) {
  const rootId = options.rootId || CONVOGLIDE_ROOT_ID;
  if (!payload || typeof payload !== "object" || !payload.mapping || !payload.current_node) {
    return { changed: false, payload, reason: "missing-shape" };
  }

  const mapping = payload.mapping;
  const branch = convoglideExtractActiveBranchIds(payload);

  if (branch.length === 0) {
    return { changed: false, payload, reason: "empty-branch" };
  }

  const trimMode = options.mode === "turn-window" ? "turn-window" : "visible-message";
  let startIndex = 0;

  if (trimMode === "turn-window") {
    startIndex = convoglideFindTurnWindowStartIndex(branch, mapping, options.turnCount);
  } else {
    let messageCount = 0;
    for (let i = branch.length - 1; i >= 0; i -= 1) {
      if (convoglideIsUserFacingMessageNode(mapping[branch[i]])) {
        messageCount += 1;
      }
      if (messageCount > maxMessageNodes) {
        startIndex = i + 1;
        break;
      }
    }
  }

  if (startIndex === 0) {
    return {
      changed: false,
      payload,
      reason: "within-limit",
      beforeNodes: Object.keys(mapping).length,
      afterNodes: Object.keys(mapping).length,
      keptMessageNodes: branch.filter((id) => convoglideIsUserFacingMessageNode(mapping[id])).length,
      mode: trimMode,
    };
  }

  const keptIds = branch.slice(startIndex);
  const rootTemplate = mapping[rootId] || {
    id: rootId,
    message: null,
    parent: null,
    children: [],
  };

  const newMapping = {
    [rootId]: {
      ...convoglideCloneValue(rootTemplate),
      parent: null,
      children: keptIds.length ? [keptIds[0]] : [],
    },
  };

  let keptMessageNodes = 0;

  for (let i = 0; i < keptIds.length; i += 1) {
    const id = keptIds[i];
    const original = mapping[id];
    if (!original) continue;
    const nextId = keptIds[i + 1] || null;
    if (convoglideIsUserFacingMessageNode(original)) {
      keptMessageNodes += 1;
    }
    newMapping[id] = {
      ...convoglideCloneValue(original),
      parent: i === 0 ? rootId : keptIds[i - 1],
      children: nextId ? [nextId] : [],
    };
  }

  return {
    changed: true,
    payload: {
      ...payload,
      mapping: newMapping,
    },
    beforeNodes: Object.keys(mapping).length,
    afterNodes: Object.keys(newMapping).length,
    keptMessageNodes,
    mode: trimMode,
  };
}

function convoglideShouldVirtualizeRect(rect, viewportHeight, bufferPx) {
  return rect.bottom < -bufferPx || rect.top > viewportHeight + bufferPx;
}

function convoglideClassifyHeavyBlockMetrics(metrics, options = {}) {
  const minHeightPx = Number.isFinite(options.minHeightPx)
    ? Math.max(160, Math.floor(options.minHeightPx))
    : CONVOGLIDE_DEFAULT_HEAVY_BLOCK_MIN_HEIGHT_PX;
  const minTextLength = Number.isFinite(options.minTextLength)
    ? Math.max(400, Math.floor(options.minTextLength))
    : CONVOGLIDE_DEFAULT_HEAVY_BLOCK_MIN_TEXT_LENGTH;

  const tagName = String(metrics?.tagName || "").toUpperCase();
  const height = Math.max(0, Math.ceil(metrics?.height || 0));
  const textLength = Math.max(0, Math.floor(metrics?.textLength || 0));
  const rowCount = Math.max(0, Math.floor(metrics?.rowCount || 0));

  if (height >= minHeightPx) {
    return true;
  }
  if (tagName === "PRE" && textLength >= minTextLength) {
    return true;
  }
  if (tagName === "TABLE" && rowCount >= 8) {
    return true;
  }
  return false;
}

function convoglideIsDocumentHidden(doc = document) {
  return doc?.visibilityState === "hidden";
}

function convoglideIsScrollableElement(element, doc = document) {
  if (!element) {
    return false;
  }
  const distance = Math.max(0, (element.scrollHeight || 0) - (element.clientHeight || 0));
  if (distance <= 32) {
    return false;
  }
  if (element === doc.scrollingElement || element === doc.documentElement || element === doc.body) {
    return true;
  }
  const style = getComputedStyle(element);
  const overflowY = style.overflowY || style.overflow || "";
  return /(auto|scroll|overlay)/.test(overflowY);
}

function convoglideFindScrollRoot(seed, doc = document) {
  const candidates = [doc.scrollingElement, doc.documentElement, doc.body].filter(Boolean);
  let cursor = seed;
  while (cursor && cursor !== doc.documentElement) {
    if (convoglideIsScrollableElement(cursor, doc)) {
      candidates.push(cursor);
    }
    cursor = cursor.parentElement;
  }

  let best = candidates[0] || doc.documentElement || doc.body;
  let bestDistance = best ? Math.max(0, best.scrollHeight - best.clientHeight) : 0;

  for (const candidate of candidates) {
    const distance = Math.max(0, candidate.scrollHeight - candidate.clientHeight);
    if (distance > bestDistance) {
      best = candidate;
      bestDistance = distance;
    }
  }

  return best;
}

function convoglideExtractConversationIdFromUrl(url) {
  const match = String(url || "").match(/\/backend-api\/conversation\/([0-9a-f-]+)(?:\?|$)/i);
  return match?.[1] || null;
}

function installConvoGlideChatGPTRuntime(options = {}) {
  const ROOT_ID = CONVOGLIDE_ROOT_ID;
  const CONVERSATION_RESPONSE_RE = CONVOGLIDE_CONVERSATION_RESPONSE_RE;
  const DEFAULT_MAX_MESSAGE_NODES = CONVOGLIDE_DEFAULT_MAX_MESSAGE_NODES;
  const DEFAULT_KEEP_TAIL_TURNS = CONVOGLIDE_DEFAULT_KEEP_TAIL_TURNS;
  const DEFAULT_BOOTSTRAP_MAX_MESSAGE_NODES = CONVOGLIDE_DEFAULT_BOOTSTRAP_MAX_MESSAGE_NODES;
  const DEFAULT_BOOTSTRAP_TURN_WINDOW = CONVOGLIDE_DEFAULT_BOOTSTRAP_TURN_WINDOW;
  const DEFAULT_VIEWPORT_BUFFER_PX = CONVOGLIDE_DEFAULT_VIEWPORT_BUFFER_PX;
  const DEFAULT_MIN_TURN_HEIGHT_PX = CONVOGLIDE_DEFAULT_MIN_TURN_HEIGHT_PX;
  const DEFAULT_HEAVY_BLOCK_BUFFER_PX = CONVOGLIDE_DEFAULT_HEAVY_BLOCK_BUFFER_PX;
  const DEFAULT_HEAVY_BLOCK_MIN_HEIGHT_PX = CONVOGLIDE_DEFAULT_HEAVY_BLOCK_MIN_HEIGHT_PX;
  const DEFAULT_HEAVY_BLOCK_MIN_TEXT_LENGTH = CONVOGLIDE_DEFAULT_HEAVY_BLOCK_MIN_TEXT_LENGTH;
  const DEFAULT_POST_LOAD_START_DELAY_MS = CONVOGLIDE_DEFAULT_POST_LOAD_START_DELAY_MS;
  const DEFAULT_POST_LOAD_FALLBACK_DELAY_MS = CONVOGLIDE_DEFAULT_POST_LOAD_FALLBACK_DELAY_MS;
  const threadSelectors = CONVOGLIDE_THREAD_SELECTORS;

  const responseHeaderName = options.responseHeaderName || "x-convoglide";
  const responseHeaderValue = options.responseHeaderValue || "trim";
  const maxMessageNodesStorageKey = options.maxMessageNodesStorageKey || "convoglide:max-message-nodes";
  const bootstrapMaxMessageNodesStorageKey = options.bootstrapMaxMessageNodesStorageKey || "convoglide:bootstrap-max-message-nodes";
  const bootstrapTurnWindowStorageKey = options.bootstrapTurnWindowStorageKey || "convoglide:bootstrap-turn-window";
  const postLoadActivation = {
    startDelayMs: Number.isFinite(options.postLoadActivation?.startDelayMs)
      ? Math.max(0, Math.floor(options.postLoadActivation.startDelayMs))
      : DEFAULT_POST_LOAD_START_DELAY_MS,
    fallbackDelayMs: Number.isFinite(options.postLoadActivation?.fallbackDelayMs)
      ? Math.max(2000, Math.floor(options.postLoadActivation.fallbackDelayMs))
      : DEFAULT_POST_LOAD_FALLBACK_DELAY_MS,
  };
  const bootstrap = {
    enabled: options.bootstrap?.enabled !== false,
    maxMessageNodes: Number.isFinite(options.bootstrap?.maxMessageNodes)
      ? Math.max(CONVOGLIDE_MIN_BOOTSTRAP_MESSAGE_NODES, Math.floor(options.bootstrap.maxMessageNodes))
      : DEFAULT_BOOTSTRAP_MAX_MESSAGE_NODES,
    turnWindow: Number.isFinite(options.bootstrap?.turnWindow)
      ? Math.max(CONVOGLIDE_MIN_BOOTSTRAP_TURN_WINDOW, Math.floor(options.bootstrap.turnWindow))
      : DEFAULT_BOOTSTRAP_TURN_WINDOW,
  };
  const conversationCache = {
    enabled: options.conversationCache?.enabled !== false,
    ttlMs: Number.isFinite(options.conversationCache?.ttlMs)
      ? Math.max(60_000, Math.floor(options.conversationCache.ttlMs))
      : CONVOGLIDE_DEFAULT_CONVERSATION_CACHE_TTL_MS,
    maxEntries: Number.isFinite(options.conversationCache?.maxEntries)
      ? Math.max(1, Math.floor(options.conversationCache.maxEntries))
      : CONVOGLIDE_DEFAULT_CONVERSATION_CACHE_MAX_ENTRIES,
    storageKey: options.conversationCache?.storageKey || CONVOGLIDE_CONVERSATION_CACHE_STORAGE_KEY,
  };
  const virtualization = {
    enabled: options.virtualization?.enabled !== false,
    keepTailTurns: Number.isFinite(options.virtualization?.keepTailTurns)
      ? Math.max(4, Math.floor(options.virtualization.keepTailTurns))
      : DEFAULT_KEEP_TAIL_TURNS,
    viewportBufferPx: Number.isFinite(options.virtualization?.viewportBufferPx)
      ? Math.max(600, Math.floor(options.virtualization.viewportBufferPx))
      : DEFAULT_VIEWPORT_BUFFER_PX,
    minTurnHeightPx: Number.isFinite(options.virtualization?.minTurnHeightPx)
      ? Math.max(80, Math.floor(options.virtualization.minTurnHeightPx))
      : DEFAULT_MIN_TURN_HEIGHT_PX,
  };
  const heavyBlocks = {
    enabled: options.heavyBlocks?.enabled !== false,
    viewportBufferPx: Number.isFinite(options.heavyBlocks?.viewportBufferPx)
      ? Math.max(400, Math.floor(options.heavyBlocks.viewportBufferPx))
      : DEFAULT_HEAVY_BLOCK_BUFFER_PX,
    minHeightPx: Number.isFinite(options.heavyBlocks?.minHeightPx)
      ? Math.max(160, Math.floor(options.heavyBlocks.minHeightPx))
      : DEFAULT_HEAVY_BLOCK_MIN_HEIGHT_PX,
    minTextLength: Number.isFinite(options.heavyBlocks?.minTextLength)
      ? Math.max(400, Math.floor(options.heavyBlocks.minTextLength))
      : DEFAULT_HEAVY_BLOCK_MIN_TEXT_LENGTH,
  };

  function notify(detail = {}) {
    try {
      window.__CONVOGLIDE_STATE = detail;
    } catch {}

    try {
      const events = Array.isArray(window.__CONVOGLIDE_EVENTS) ? window.__CONVOGLIDE_EVENTS : [];
      events.push({
        at: Date.now(),
        ...detail,
      });
      window.__CONVOGLIDE_EVENTS = events.slice(-50);
    } catch {}

    if (typeof options.report === "function") {
      options.report(detail);
    }
  }

  function getMaxMessageNodes() {
    const raw = localStorage.getItem(maxMessageNodesStorageKey);
    const value = Number(raw || DEFAULT_MAX_MESSAGE_NODES);
    return Number.isFinite(value) && value >= CONVOGLIDE_MIN_MAX_MESSAGE_NODES
      ? Math.floor(value)
      : DEFAULT_MAX_MESSAGE_NODES;
  }

  function trimConversationPayload(payload, maxMessageNodes) {
    return convoglideTrimConversationPayload(payload, maxMessageNodes, { rootId: ROOT_ID });
  }

  function trimBootstrapPayload(payload, maxMessageNodes, turnWindow) {
    return convoglideTrimConversationPayload(payload, maxMessageNodes, {
      rootId: ROOT_ID,
      mode: "turn-window",
      turnCount: turnWindow,
    });
  }

  function getBootstrapMaxMessageNodes() {
    const raw = localStorage.getItem(bootstrapMaxMessageNodesStorageKey);
    const stored = Number(raw);
    if (Number.isFinite(stored) && stored >= CONVOGLIDE_MIN_BOOTSTRAP_MESSAGE_NODES) {
      return Math.floor(stored);
    }
    return bootstrap.maxMessageNodes;
  }

  function getBootstrapTurnWindow(maxMessageNodes) {
    const raw = localStorage.getItem(bootstrapTurnWindowStorageKey);
    const stored = Number(raw);
    return convoglideResolveBootstrapTurnWindow(maxMessageNodes, {
      bootstrapTurnWindow: Number.isFinite(stored) ? stored : bootstrap.turnWindow,
    });
  }

  function resolveBootstrapMaxMessageNodes(maxMessageNodes) {
    if (!bootstrap.enabled) {
      return maxMessageNodes;
    }
    return convoglideResolveBootstrapMaxMessageNodes(maxMessageNodes, {
      bootstrapMaxMessageNodes: getBootstrapMaxMessageNodes(),
    });
  }

  function readConversationCacheStore() {
    if (!conversationCache.enabled) {
      return {};
    }
    try {
      const raw = localStorage.getItem(conversationCache.storageKey);
      if (!raw) {
        return {};
      }
      const parsed = JSON.parse(raw);
      return parsed && typeof parsed === "object" ? parsed : {};
    } catch {
      return {};
    }
  }

  function writeConversationCacheStore(store) {
    if (!conversationCache.enabled) {
      return;
    }
    try {
      localStorage.setItem(conversationCache.storageKey, JSON.stringify(store));
    } catch {}
  }

  function getConversationCacheKey(conversationId, maxMessageNodes) {
    return `${conversationId}:keep:${maxMessageNodes}`;
  }

  function readConversationCacheEntry(conversationId, maxMessageNodes) {
    if (!conversationCache.enabled || !conversationId) {
      return null;
    }

    const store = readConversationCacheStore();
    const key = getConversationCacheKey(conversationId, maxMessageNodes);
    const entry = store[key];
    if (!entry || typeof entry !== "object") {
      return null;
    }

    const ageMs = Date.now() - Number(entry.savedAt || 0);
    if (!Number.isFinite(ageMs) || ageMs < 0 || ageMs > conversationCache.ttlMs) {
      delete store[key];
      writeConversationCacheStore(store);
      return null;
    }

    return entry;
  }

  function writeConversationCacheEntry(conversationId, maxMessageNodes, text) {
    if (!conversationCache.enabled || !conversationId || typeof text !== "string") {
      return;
    }

    const store = readConversationCacheStore();
    const nextKey = getConversationCacheKey(conversationId, maxMessageNodes);
    store[nextKey] = {
      conversationId,
      maxMessageNodes,
      text,
      savedAt: Date.now(),
    };

    const entries = Object.entries(store).sort(
      (left, right) => Number(right[1]?.savedAt || 0) - Number(left[1]?.savedAt || 0),
    );
    const trimmedStore = {};
    for (const [key, value] of entries.slice(0, conversationCache.maxEntries)) {
      trimmedStore[key] = value;
    }
    writeConversationCacheStore(trimmedStore);
  }

  function maybeRewriteResponseText(url, text, options = {}) {
    if (!CONVERSATION_RESPONSE_RE.test(url)) {
      return null;
    }

    const maxMessageNodes = getMaxMessageNodes();
    const payload = JSON.parse(text);
    const fullTrim = trimConversationPayload(payload, maxMessageNodes);
    const conversationId = convoglideExtractConversationIdFromUrl(url);

    let activeTrim = fullTrim;
    let mode = "configured";

    if (options.preferBootstrap) {
      const bootstrapTurnWindow = getBootstrapTurnWindow(maxMessageNodes);
      const bootstrapTrim = trimBootstrapPayload(payload, maxMessageNodes, bootstrapTurnWindow);
      if (bootstrapTrim.changed || bootstrapTrim.reason === "within-limit") {
        activeTrim = bootstrapTrim;
        mode = `bootstrap:${bootstrapTurnWindow}turns`;
      }
    }

    const cacheText = fullTrim.changed ? JSON.stringify(fullTrim.payload) : text;
    writeConversationCacheEntry(conversationId, maxMessageNodes, cacheText);

    if (!activeTrim.changed) {
      notify({
        phase: mode === "configured" ? "fetch-pass" : "fetch-bootstrap",
        summary:
          mode === "configured"
            ? `${activeTrim.reason || "pass"} ${activeTrim.afterNodes || 0} nodes`
            : `bootstrap keep ${activeTrim.keptMessageNodes} visible via ${activeTrim.mode || "turn-window"} (cache keep ${maxMessageNodes})`,
        url,
      });
      return mode === "configured" ? null : text;
    }

    notify({
      phase: mode === "configured" ? "fetch-trim" : "fetch-bootstrap",
        summary:
        mode === "configured"
          ? `${activeTrim.beforeNodes} -> ${activeTrim.afterNodes} nodes (keep ${activeTrim.keptMessageNodes} visible)`
          : `${activeTrim.beforeNodes} -> ${activeTrim.afterNodes} nodes (bootstrap keep ${activeTrim.keptMessageNodes} visible via ${activeTrim.mode || "turn-window"}, cache keep ${maxMessageNodes})`,
      url,
    });

    return JSON.stringify(activeTrim.payload);
  }

  function installFetchHook() {
    const originalFetch = window.fetch.bind(window);

    window.fetch = async (...args) => {
      try {
        const request = args[0];
        const url =
          typeof request === "string"
            ? request
            : request instanceof Request
              ? request.url
              : String(request);

        const method =
          request instanceof Request
            ? request.method
            : typeof args[1]?.method === "string"
              ? args[1].method
              : "GET";

        const isConversationGet = CONVERSATION_RESPONSE_RE.test(url) && String(method).toUpperCase() === "GET";
        const conversationId = isConversationGet ? convoglideExtractConversationIdFromUrl(url) : null;
        const maxMessageNodes = isConversationGet ? getMaxMessageNodes() : null;
        const cached = isConversationGet ? readConversationCacheEntry(conversationId, maxMessageNodes) : null;

        if (isConversationGet) {
          if (cached?.text) {
            notify({
              phase: "cache-hit",
              summary: `reuse local cache keep=${maxMessageNodes}`,
              url,
            });

            originalFetch(...args)
              .then(async (refreshResponse) => {
                try {
                  const contentType = refreshResponse.headers.get("content-type") || "";
                  if (!contentType.includes("application/json")) {
                    return;
                  }
                  const refreshText = await refreshResponse.clone().text();
                  maybeRewriteResponseText(url, refreshText, { preferBootstrap: false });
                } catch (error) {
                  notify({
                    phase: "cache-refresh-error",
                    summary: error instanceof Error ? error.message : String(error),
                    url,
                  });
                }
              })
              .catch((error) => {
                notify({
                  phase: "cache-refresh-error",
                  summary: error instanceof Error ? error.message : String(error),
                  url,
                });
              });

            return new Response(cached.text, {
              status: 200,
              statusText: "OK",
              headers: {
                "content-type": "application/json; charset=utf-8",
                [responseHeaderName]: "cache-hit",
              },
            });
          }
        }

        const response = await originalFetch(...args);
        if (!isConversationGet) {
          return response;
        }

        const contentType = response.headers.get("content-type") || "";
        if (!contentType.includes("application/json")) {
          notify({
            phase: "fetch-skip",
            summary: `non-json ${contentType || "unknown"}`,
            url,
          });
          return response;
        }

        const rawText = await response.clone().text();
        const rewrittenText = maybeRewriteResponseText(url, rawText, {
          preferBootstrap: !cached,
        });
        if (!rewrittenText) {
          return response;
        }

        const headers = new Headers(response.headers);
        headers.delete("content-length");
        headers.set(responseHeaderName, responseHeaderValue);

        return new Response(rewrittenText, {
          status: response.status,
          statusText: response.statusText,
          headers,
        });
      } catch (error) {
        notify({
          phase: "fetch-error",
          summary: error instanceof Error ? error.message : String(error),
          url: location.pathname,
        });
        return response;
      }
    };
  }

  function createTurnVirtualizer() {
    const snapshots = new WeakMap();
    let scheduled = false;
    let threadRoot = null;
    let threadObserver = null;
    let discoveryObserver = null;
    let restoreBoundRoot = null;
    let scrollTarget = null;
    let scrollTimer = null;
    let pauseUntil = 0;
    let lastSummary = "";

    function findThreadRoot() {
      for (const selector of threadSelectors) {
        const node = document.querySelector(selector);
        if (node) {
          return node;
        }
      }
      return null;
    }

    function getTurnElements(root) {
      if (!root) {
        return [];
      }

      const sections = Array.from(root.querySelectorAll('section[data-testid^="conversation-turn-"]'));
      if (sections.length) {
        return sections;
      }

      const articles = Array.from(root.querySelectorAll("article"));
      if (articles.length) {
        return articles;
      }

      return Array.from(root.querySelectorAll("[data-message-id]")).filter((element) => {
        const parentMessage = element.parentElement?.closest?.("[data-message-id]");
        return !parentMessage;
      });
    }

    function restoreTurn(turn) {
      const snapshot = snapshots.get(turn);
      if (!snapshot) {
        return false;
      }

      turn.replaceChildren(...snapshot.nodes);
      turn.style.minHeight = "";
      turn.removeAttribute("data-convoglide-virtualized");
      snapshots.delete(turn);
      return true;
    }

    function restoreAllTurns(root = threadRoot) {
      if (!root) {
        return;
      }
      for (const turn of getTurnElements(root)) {
        restoreTurn(turn);
      }
    }

    function virtualizeTurn(turn) {
      if (snapshots.has(turn)) {
        return false;
      }
      if (turn.contains(document.activeElement)) {
        return false;
      }

      const nodes = Array.from(turn.childNodes);
      if (!nodes.length) {
        return false;
      }

      const rect = turn.getBoundingClientRect();
      const height = Math.max(
        virtualization.minTurnHeightPx,
        Math.ceil(rect.height || 0),
        Math.ceil(turn.offsetHeight || 0),
      );

      const placeholder = document.createElement("div");
      placeholder.className = "convoglide-placeholder";
      placeholder.style.height = `${height}px`;
      placeholder.tabIndex = 0;
      placeholder.setAttribute("role", "button");
      placeholder.setAttribute("aria-label", "Restore off-screen conversation content");
      placeholder.setAttribute("title", "Restore this conversation turn");
      placeholder.innerHTML = [
        '<span class="convoglide-placeholder__label">ConvoGlide virtualized off-screen content. Click to restore.</span>',
      ].join("");

      snapshots.set(turn, {
        nodes,
        height,
      });
      turn.replaceChildren(placeholder);
      turn.style.minHeight = `${height}px`;
      turn.setAttribute("data-convoglide-virtualized", "true");
      return true;
    }

    function shouldVirtualizeTurn(turn) {
      const rect = turn.getBoundingClientRect();
      const buffer = virtualization.viewportBufferPx;
      return convoglideShouldVirtualizeRect(rect, window.innerHeight, buffer);
    }

    function summarize(turns, virtualizedCount) {
      const summary = `virtualized ${virtualizedCount}/${turns.length} turns`;
      if (summary !== lastSummary) {
        lastSummary = summary;
        notify({
          phase: "virtualizer",
          summary,
          url: location.pathname,
        });
      }
    }

    function scheduleFromScroll() {
      clearTimeout(scrollTimer);
      scrollTimer = setTimeout(() => {
        scrollTimer = null;
        schedule();
      }, 120);
    }

    function bindScrollTarget(root = threadRoot) {
      if (!root?.isConnected) {
        return;
      }

      const nextElement = convoglideFindScrollRoot(root);
      const nextEventTarget =
        nextElement === document.scrollingElement || nextElement === document.documentElement || nextElement === document.body
          ? window
          : nextElement;

      if (scrollTarget?.eventTarget === nextEventTarget && scrollTarget?.element === nextElement) {
        return;
      }

      if (scrollTarget?.eventTarget) {
        scrollTarget.eventTarget.removeEventListener("scroll", scheduleFromScroll);
      }

      scrollTarget = {
        element: nextElement,
        eventTarget: nextEventTarget,
      };

      scrollTarget.eventTarget?.addEventListener("scroll", scheduleFromScroll, { passive: true });
    }

    function run() {
      if (!threadRoot || !threadRoot.isConnected) {
        attach(findThreadRoot());
        return;
      }

      bindScrollTarget(threadRoot);

      if (convoglideIsDocumentHidden()) {
        return;
      }

      if (Date.now() < pauseUntil) {
        restoreAllTurns(threadRoot);
        summarize(getTurnElements(threadRoot), 0);
        return;
      }

      const turns = getTurnElements(threadRoot);
      if (!turns.length) {
        return;
      }

      const keepTailStart = Math.max(0, turns.length - virtualization.keepTailTurns);
      let virtualizedCount = 0;

      for (let index = 0; index < turns.length; index += 1) {
        const turn = turns[index];
        if (index >= keepTailStart) {
          restoreTurn(turn);
          continue;
        }

        if (shouldVirtualizeTurn(turn)) {
          if (virtualizeTurn(turn)) {
            virtualizedCount += 1;
          } else if (snapshots.has(turn)) {
            virtualizedCount += 1;
          }
        } else {
          restoreTurn(turn);
        }
      }

      summarize(turns, virtualizedCount);
    }

    function schedule() {
      if (scheduled) {
        return;
      }
      scheduled = true;
      requestAnimationFrame(() => {
        scheduled = false;
        run();
      });
    }

    function attach(root) {
      if (!root) {
        return;
      }
      if (threadRoot === root) {
        schedule();
        return;
      }

      threadRoot = root;
      bindScrollTarget(root);
      threadObserver?.disconnect();
      threadObserver = new MutationObserver(() => {
        bindScrollTarget(threadRoot);
        schedule();
      });
      threadObserver.observe(threadRoot, {
        childList: true,
        subtree: true,
      });
      schedule();
    }

    function bindRestoreInteractions(root) {
      if (!root || restoreBoundRoot === root) {
        return;
      }

      restoreBoundRoot = root;

      root.addEventListener("click", (event) => {
        const placeholder = event.target?.closest?.(".convoglide-placeholder");
        const turn = placeholder?.closest?.('[data-convoglide-virtualized="true"]');
        if (!turn) {
          return;
        }
        if (restoreTurn(turn)) {
          notify({
            phase: "virtualizer-restore",
            summary: "restored turn from placeholder click",
            url: location.pathname,
          });
          schedule();
        }
      });

      root.addEventListener("keydown", (event) => {
        if (event.key !== "Enter" && event.key !== " ") {
          return;
        }
        const placeholder = event.target?.closest?.(".convoglide-placeholder");
        const turn = placeholder?.closest?.('[data-convoglide-virtualized="true"]');
        if (!turn) {
          return;
        }
        event.preventDefault();
        if (restoreTurn(turn)) {
          notify({
            phase: "virtualizer-restore",
            summary: "restored turn from placeholder keyboard",
            url: location.pathname,
          });
          schedule();
        }
      });
    }

    function watchForThreadRoot() {
      const root = findThreadRoot();
      if (root) {
        discoveryObserver?.disconnect();
        attach(root);
        bindRestoreInteractions(root);
        return;
      }

      if (discoveryObserver) {
        return;
      }

      discoveryObserver = new MutationObserver(() => {
        const nextRoot = findThreadRoot();
        if (nextRoot) {
          discoveryObserver?.disconnect();
          discoveryObserver = null;
          attach(nextRoot);
          bindRestoreInteractions(nextRoot);
        }
      });
      discoveryObserver.observe(document, {
        childList: true,
        subtree: true,
      });
    }

    window.addEventListener("resize", schedule, { passive: true });
    window.addEventListener("load", schedule, { once: true });
    document.addEventListener("visibilitychange", () => {
      if (!convoglideIsDocumentHidden()) {
        schedule();
      }
    });

    document.addEventListener("keydown", (event) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "f") {
        pauseUntil = Date.now() + 15000;
        restoreAllTurns(threadRoot);
        notify({
          phase: "virtualizer-pause",
          summary: "pause virtualization for in-page search",
          url: location.pathname,
        });
        setTimeout(schedule, 16000);
      }
    });

    watchForThreadRoot();
  }

  function installVirtualizer() {
    if (!virtualization.enabled) {
      return;
    }
    createTurnVirtualizer();
  }

  function createHeavyBlockLazyActivator() {
    const deferredBlocks = new Map();
    let scheduled = false;
    let threadRoot = null;
    let threadObserver = null;
    let discoveryObserver = null;
    let restoreBoundRoot = null;
    let scrollTarget = null;
    let scrollTimer = null;
    let pauseUntil = 0;
    let lastSummary = "";
    const heavyClassificationCache = new WeakMap();

    function findThreadRoot() {
      for (const selector of threadSelectors) {
        const node = document.querySelector(selector);
        if (node) {
          return node;
        }
      }
      return null;
    }

    function getHeavyBlocks(root) {
      if (!root) {
        return [];
      }
      return Array.from(root.querySelectorAll("pre, table"));
    }

    function getHeavyPlaceholders(root) {
      if (!root) {
        return [];
      }
      return Array.from(root.querySelectorAll('[data-convoglide-heavy-placeholder="true"]'));
    }

    function isNearViewport(element) {
      const rect = element.getBoundingClientRect();
      const buffer = heavyBlocks.viewportBufferPx;
      return rect.bottom >= -buffer && rect.top <= window.innerHeight + buffer;
    }

    function isHeavyBlock(element) {
      const cached = heavyClassificationCache.get(element);
      if (typeof cached === "boolean") {
        return cached;
      }
      const rect = element.getBoundingClientRect();
      const result = convoglideClassifyHeavyBlockMetrics(
        {
          tagName: element.tagName,
          height: Math.max(Math.ceil(rect.height || 0), Math.ceil(element.offsetHeight || 0)),
          textLength: (element.textContent || "").length,
          rowCount: element.tagName === "TABLE" ? element.querySelectorAll("tr").length : 0,
        },
        heavyBlocks,
      );
      heavyClassificationCache.set(element, result);
      return result;
    }

    function applyMediaHints(root) {
      if (!root) {
        return;
      }

      for (const image of root.querySelectorAll("img")) {
        if (image.dataset.convoglideHinted === "true") continue;
        if (!image.hasAttribute("loading")) image.setAttribute("loading", "lazy");
        if (!image.hasAttribute("decoding")) image.setAttribute("decoding", "async");
        if (!image.hasAttribute("fetchpriority")) image.setAttribute("fetchpriority", "low");
        image.dataset.convoglideHinted = "true";
      }

      for (const iframe of root.querySelectorAll("iframe")) {
        if (iframe.dataset.convoglideHinted === "true") continue;
        if (!iframe.hasAttribute("loading")) iframe.setAttribute("loading", "lazy");
        iframe.dataset.convoglideHinted = "true";
      }

      for (const video of root.querySelectorAll("video")) {
        if (video.dataset.convoglideHinted === "true") continue;
        if (!video.hasAttribute("preload")) video.setAttribute("preload", "metadata");
        video.dataset.convoglideHinted = "true";
      }
    }

    function cleanupDetachedPlaceholders() {
      for (const [placeholder] of deferredBlocks) {
        if (!placeholder.isConnected) {
          deferredBlocks.delete(placeholder);
        }
      }
    }

    function restorePlaceholder(placeholder) {
      const snapshot = deferredBlocks.get(placeholder);
      if (!snapshot) {
        return false;
      }
      if (!placeholder.isConnected) {
        deferredBlocks.delete(placeholder);
        return false;
      }
      placeholder.replaceWith(snapshot.element);
      deferredBlocks.delete(placeholder);
      return true;
    }

    function deferBlock(element) {
      if (!element.isConnected) {
        return false;
      }
      if (element.contains(document.activeElement)) {
        return false;
      }

      const rect = element.getBoundingClientRect();
      const height = Math.max(
        heavyBlocks.minHeightPx,
        Math.ceil(rect.height || 0),
        Math.ceil(element.offsetHeight || 0),
      );

      const placeholder = document.createElement("div");
      placeholder.className = "convoglide-heavy-placeholder";
      placeholder.style.height = `${height}px`;
      placeholder.tabIndex = 0;
      placeholder.setAttribute("role", "button");
      placeholder.setAttribute("aria-label", `Restore deferred ${element.tagName.toLowerCase()} block`);
      placeholder.setAttribute("title", `Restore this ${element.tagName.toLowerCase()} block`);
      placeholder.setAttribute("data-convoglide-heavy-placeholder", "true");
      placeholder.setAttribute("data-convoglide-heavy-kind", element.tagName.toLowerCase());
      placeholder.innerHTML = [
        `<span class="convoglide-heavy-placeholder__label">ConvoGlide deferred ${element.tagName.toLowerCase()} block. Click to restore.</span>`,
      ].join("");

      element.replaceWith(placeholder);
      deferredBlocks.set(placeholder, {
        element,
        height,
      });
      return true;
    }

    function summarize(count) {
      const summary = `deferred ${count} heavy blocks`;
      if (summary !== lastSummary) {
        lastSummary = summary;
        notify({
          phase: "lazy-heavy",
          summary,
          url: location.pathname,
        });
      }
    }

    function scheduleFromScroll() {
      clearTimeout(scrollTimer);
      scrollTimer = setTimeout(() => {
        scrollTimer = null;
        schedule();
      }, 120);
    }

    function bindScrollTarget(root = threadRoot) {
      if (!root?.isConnected) {
        return;
      }

      const nextElement = convoglideFindScrollRoot(root);
      const nextEventTarget =
        nextElement === document.scrollingElement || nextElement === document.documentElement || nextElement === document.body
          ? window
          : nextElement;

      if (scrollTarget?.eventTarget === nextEventTarget && scrollTarget?.element === nextElement) {
        return;
      }

      if (scrollTarget?.eventTarget) {
        scrollTarget.eventTarget.removeEventListener("scroll", scheduleFromScroll);
      }

      scrollTarget = {
        element: nextElement,
        eventTarget: nextEventTarget,
      };

      scrollTarget.eventTarget?.addEventListener("scroll", scheduleFromScroll, { passive: true });
    }

    function run() {
      if (!threadRoot || !threadRoot.isConnected) {
        attach(findThreadRoot());
        return;
      }

      bindScrollTarget(threadRoot);

      if (convoglideIsDocumentHidden()) {
        return;
      }

      applyMediaHints(threadRoot);
      cleanupDetachedPlaceholders();

      if (Date.now() < pauseUntil) {
        for (const placeholder of getHeavyPlaceholders(threadRoot)) {
          restorePlaceholder(placeholder);
        }
        summarize(0);
        return;
      }

      let deferredCount = 0;

      for (const placeholder of getHeavyPlaceholders(threadRoot)) {
        if (isNearViewport(placeholder)) {
          restorePlaceholder(placeholder);
        } else {
          deferredCount += 1;
        }
      }

      for (const block of getHeavyBlocks(threadRoot)) {
        if (block.closest('[data-convoglide-virtualized="true"]')) {
          continue;
        }
        if (isNearViewport(block)) {
          continue;
        }
        if (!isHeavyBlock(block)) {
          continue;
        }
        if (deferBlock(block)) {
          deferredCount += 1;
        }
      }

      summarize(deferredCount);
    }

    function schedule() {
      if (scheduled) {
        return;
      }
      scheduled = true;
      requestAnimationFrame(() => {
        scheduled = false;
        run();
      });
    }

    function attach(root) {
      if (!root) {
        return;
      }
      if (threadRoot === root) {
        schedule();
        return;
      }

      threadRoot = root;
      bindScrollTarget(root);
      threadObserver?.disconnect();
      threadObserver = new MutationObserver(() => {
        bindScrollTarget(threadRoot);
        schedule();
      });
      threadObserver.observe(threadRoot, {
        childList: true,
        subtree: true,
      });
      schedule();
    }

    function bindRestoreInteractions(root) {
      if (!root || restoreBoundRoot === root) {
        return;
      }

      restoreBoundRoot = root;

      function restoreFromTarget(target, source) {
        const placeholder = target?.closest?.('[data-convoglide-heavy-placeholder="true"]');
        if (!placeholder) {
          return false;
        }
        if (restorePlaceholder(placeholder)) {
          notify({
            phase: "lazy-heavy-restore",
            summary: `restored heavy block from ${source}`,
            url: location.pathname,
          });
          schedule();
          return true;
        }
        return false;
      }

      root.addEventListener("click", (event) => {
        restoreFromTarget(event.target, "click");
      });

      root.addEventListener("keydown", (event) => {
        if (event.key !== "Enter" && event.key !== " ") {
          return;
        }
        if (restoreFromTarget(event.target, "keyboard")) {
          event.preventDefault();
        }
      });
    }

    function watchForThreadRoot() {
      const root = findThreadRoot();
      if (root) {
        discoveryObserver?.disconnect();
        attach(root);
        bindRestoreInteractions(root);
        return;
      }

      if (discoveryObserver) {
        return;
      }

      discoveryObserver = new MutationObserver(() => {
        const nextRoot = findThreadRoot();
        if (nextRoot) {
          discoveryObserver?.disconnect();
          discoveryObserver = null;
          attach(nextRoot);
          bindRestoreInteractions(nextRoot);
        }
      });
      discoveryObserver.observe(document, {
        childList: true,
        subtree: true,
      });
    }

    window.addEventListener("resize", schedule, { passive: true });
    window.addEventListener("load", schedule, { once: true });
    document.addEventListener("visibilitychange", () => {
      if (!convoglideIsDocumentHidden()) {
        schedule();
      }
    });

    document.addEventListener("keydown", (event) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "f") {
        pauseUntil = Date.now() + 15000;
        for (const placeholder of getHeavyPlaceholders(threadRoot)) {
          restorePlaceholder(placeholder);
        }
        notify({
          phase: "lazy-heavy-pause",
          summary: "pause heavy block deferral for in-page search",
          url: location.pathname,
        });
        setTimeout(schedule, 16000);
      }
    });

    watchForThreadRoot();
  }

  function installHeavyBlockLazyActivation() {
    if (!heavyBlocks.enabled) {
      return;
    }
    createHeavyBlockLazyActivator();
  }

  installFetchHook();

  let postLoadStarted = false;
  let postLoadTimer = null;
  let postLoadFallbackTimer = null;
  let postLoadTitleObserver = null;

  function startPostLoadOptimizers(reason) {
    if (postLoadStarted) {
      return;
    }
    postLoadStarted = true;
    if (postLoadTimer) {
      clearTimeout(postLoadTimer);
      postLoadTimer = null;
    }
    if (postLoadFallbackTimer) {
      clearTimeout(postLoadFallbackTimer);
      postLoadFallbackTimer = null;
    }
    postLoadTitleObserver?.disconnect();
    postLoadTitleObserver = null;
    installVirtualizer();
    installHeavyBlockLazyActivation();
    notify({
      phase: "post-load",
      summary: `started ${reason}`,
      url: location.pathname,
    });
  }

  function schedulePostLoadStart(reason) {
    if (postLoadStarted || postLoadTimer) {
      return;
    }
    postLoadTimer = setTimeout(() => {
      postLoadTimer = null;
      startPostLoadOptimizers(reason);
    }, postLoadActivation.startDelayMs);
  }

  function armPostLoadActivation() {
    const titleLooksResolved = () => {
      const title = String(document.title || "").trim();
      return title.length > 0 && title !== "ChatGPT";
    };

    if (titleLooksResolved()) {
      schedulePostLoadStart("title-ready");
    } else {
      const titleElement = document.querySelector("title") || document.head || document.documentElement;
      postLoadTitleObserver = new MutationObserver(() => {
        if (titleLooksResolved()) {
          schedulePostLoadStart("title-ready");
        }
      });
      if (titleElement) {
        postLoadTitleObserver.observe(titleElement, {
          childList: true,
          characterData: true,
          subtree: true,
        });
      }
    }

    postLoadFallbackTimer = setTimeout(() => {
      postLoadFallbackTimer = null;
      startPostLoadOptimizers("fallback");
    }, postLoadActivation.fallbackDelayMs);

    const startFromInteraction = () => {
      schedulePostLoadStart("user-interaction");
      window.removeEventListener("pointerdown", startFromInteraction, true);
      window.removeEventListener("keydown", startFromInteraction, true);
      window.removeEventListener("wheel", startFromInteraction, true);
      window.removeEventListener("touchstart", startFromInteraction, true);
    };

    window.addEventListener("pointerdown", startFromInteraction, { capture: true, passive: true });
    window.addEventListener("keydown", startFromInteraction, { capture: true });
    window.addEventListener("wheel", startFromInteraction, { capture: true, passive: true });
    window.addEventListener("touchstart", startFromInteraction, { capture: true, passive: true });
  }

  armPostLoadActivation();

  const api = {
    getEvents() {
      return Array.isArray(window.__CONVOGLIDE_EVENTS) ? [...window.__CONVOGLIDE_EVENTS] : [];
    },
    setMaxMessageNodes(value) {
      const nextValue = Math.max(CONVOGLIDE_MIN_MAX_MESSAGE_NODES, Math.floor(Number(value) || DEFAULT_MAX_MESSAGE_NODES));
      localStorage.setItem(maxMessageNodesStorageKey, String(nextValue));
      notify({
        phase: "config",
        summary: `set keep=${nextValue}; reload to apply`,
        url: location.pathname,
      });
      return nextValue;
    },
    clearMaxMessageNodes() {
      localStorage.removeItem(maxMessageNodesStorageKey);
      notify({
        phase: "config",
        summary: `reset keep=${DEFAULT_MAX_MESSAGE_NODES}; reload to apply`,
        url: location.pathname,
      });
    },
  };

  window.ConvoGlide = api;
  notify({
    phase: options.mode || "runtime",
    summary: `installed keep=${getMaxMessageNodes()}`,
    url: location.pathname,
  });
  return api;
}

(() => {
  const DEBUG_EVENT = "__convoglide_debug";

  function emit(detail = {}) {
    try {
      document.documentElement.dataset.convoglidePhase = detail.phase || "extension";
      document.documentElement.dataset.convoglideSummary = String(detail.summary || "").slice(0, 120);
    } catch {}

    try {
      window.dispatchEvent(
        new CustomEvent(DEBUG_EVENT, {
          detail,
        }),
      );
    } catch {}
  }

  installConvoGlideChatGPTRuntime({
    mode: "extension",
    responseHeaderValue: "extension-trim",
    report: emit,
  });
})();